source "https://rubygems.org"

ruby "3.2.2"

# Rails API
gem "rails", "~> 7.1.0"
gem "pg", "~> 1.4"
gem "puma", "~> 6.1"
gem "bootsnap", ">= 1.21.0", require: false

# JSON serialization
gem "jsonapi-serializer"

# Environment variables
gem "dotenv-rails", groups: [:development, :test]

# Testing
group :development, :test do
  gem "rspec-rails", "~> 6.1"
end

# HTTP requests
gem "httparty"
